services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: mytasks
      POSTGRES_USER: mytasks
      POSTGRES_PASSWORD: mytasks@2025
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - mytasks_network

  task-service:
    build:
      context: ../apps/task-service
      dockerfile: dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - mytasks_network

volumes:
  pgdata:

networks:
  mytasks_network:
    driver: bridge
    