export const ConfirmationCode = {
  NOT_FOUND: 'AUTH.CONFIRMATION_CODE.NOT_FOUND',
  EXPIRED: 'AUTH.CONFIRMATION_CODE.EXPIRED',
  ALREADY_USED: 'AUTH.CONFIRMATION_CODE.ALREADY_USED',
  INVALID: 'AUTH.CONFIRMATION_CODE.INVALID',
} as const;

export const AccountCode = {
  ALREADY_EXISTS: 'AUTH.ACCOUNT.ALREADY_EXISTS',
} as const;
